java_avro_library(
    name='people',
    sources=['people.avdl'],
    output_format='specific',
    dependencies=[
      '3rdparty/jvm:avro',
    ],
)

java_avro_library(
    name='example',
    sources=['example.avsc'],
    output_format='specific',
    dependencies=[
      '3rdparty/jvm:avro',
    ],
)
